name: Fetch Expert Agent XML (direct download + debug)

on:
  schedule:
    - cron: "0 * * * *"   # hourly (UTC)
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      # Debug: show where we are and what the server lists at root
      - name: FTP root listing (debug)
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          set -e
          echo "Connecting and listing root..."
          lftp -u "$FTP_USER","$FTP_PASS" "$FTP_HOST" -e \
            "set ftp:passive-mode true; set ftp:ssl-force true; set ftp:ssl-protect-data true; set ssl:verify-certificate no; pwd; ls -la; bye"

      # Direct download with multiple path attempts
      - name: Download properties.xml (fallback to properties2.xml) with verbose attempts
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          set -euo pipefail
          mkdir -p tmp

          try_get () {
            PATH_TRY="$1"
            echo "Attempting: get \"$PATH_TRY\" -> tmp/new.xml"
            lftp -u "$FTP_USER","$FTP_PASS" "$FTP_HOST" -e \
              "set ftp:passive-mode true; set ftp:ssl-force true; set ftp:ssl-protect-data true; set ssl:verify-certificate no; debug 3; get \"$PATH_TRY\" -o tmp/new.xml; bye"
          }

          SUCCESS=0
          # Try common variants for both files
          for F in "properties.xml" "/properties.xml" "./properties.xml" \
                   "properties2.xml" "/properties2.xml" "./properties2.xml"; do
            if try_get "$F"; then SUCCESS=1; echo "Downloaded using path: $F"; break; fi
            echo "Failed: $F"
          done

          if [ "$SUCCESS" -ne 1 ]; then
            echo "Could not download properties.xml or properties2.xml with any path variant"
            exit 1
          fi

          # Replace repo file only if changed
          if [ ! -f properties.xml ] || ! cmp -s tmp/new.xml properties.xml; then
            mv tmp/new.xml properties.xml
            echo "UPDATED=1" >> $GITHUB_ENV
            echo "properties.xml updated"
          else
            echo "No change in properties.xml"
          fi

      - name: Commit and push if changed
        if: env.UPDATED == '1'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add properties.xml
          git commit -m "Update properties.xml from FTP (direct download)"
          git push
