name: Fetch Expert Agent XML (direct download + debug)

on:
  schedule:
    - cron: "0 * * * *"   # hourly (UTC)
  workflow_dispatch: {}

# allow this workflow to push back to the repo
permissions:
  contents: write

# avoid two runs pushing at the same time
concurrency:
  group: update-properties-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      # Debug: show root listing so we can see what's visible on the server
      - name: FTP root listing (debug)
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          set -e
          echo "Connecting and listing root..."
          lftp -u "$FT
